version: "3.8"
services:
  backend:
    build: .
    ports:
      - "9000:9000"
    command: npm run dev # Use nodemon for live reloading
    volumes:
      - ./:/app # Sync local root  directory with container
      # - ./src:/app/src # Sync local src directory with container
      - /app/node_modules # Prevent overwriting node_modules
    environment:
      - NODE_ENV=development
#   db:
#     image: postgres:latest
#     environment:
#       POSTGRES_USER: user
#       POSTGRES_PASSWORD: pass
#       POSTGRES_DB: mydb
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:
